services:
    maileva.api:
        class: Maileva\Services\Api
        arguments: ['%maileva.application_name%']
        tags:
            - { name: monolog.logger, channel: maileva }
        calls:
            - [ setLogger, [ '@logger' ]]